version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: teach-postgres
    environment:
      POSTGRES_DB: teach_db
      POSTGRES_USER: teach_user
      POSTGRES_PASSWORD: teach_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teach_user -d teach_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: teach-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment when ready to run the backend
  # backend:
  #   build: ./backend
  #   container_name: teach-backend
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_URL: postgresql://teach_user:teach_pass@postgres:5432/teach_db
  #     REDIS_URL: redis://redis:6379
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   command: npm run dev

volumes:
  postgres_data:
  redis_data: