[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.build]
cmds = [
  'cd backend',
  'npm ci',
  'npm run build'
]

[phases.start]
cmd = 'cd backend && npm run start:prod'

[variables]
NODE_ENV = 'production'